### ISSUE TITLE
successfully built dlls from https://assendelft.webathome.org/Pdfium/ did not work, they are broken

### ISSUE THREAD

**Issue by greiffa** [pvginkel/PdfiumBuild#5]
Dear Van Ginkel,

first of all, thank you very much for your great PDF Projects.

i have tried to use the pdfium.dll from your builtserver https://assendelft.webathome.org/Pdfium/ for a project of mine.
The problem is, that the build seems to be built successfull, but when i try to put it into my project references it says that the .dll is corrupt.

For example: all builts from the 2018-01-07 are corrupt.

is it maybe possible that you upload a current working version of the pdfium.dll?

Thanks you very much,

Andreas Greiff

**Comment by pvginkel** [comment]
I'm not sure if this fixes your issue, but the builds were failing because the build scripts changed again. Let's see if this fixes your problem. If not, please feel free to reply to this ticket.

**Comment by greiffa** [comment]
thank you very much for your fast answer.
I have tested the 5 succeeded version from 2018-01-25 and they still have a problem.
When i try to reference them to my projekt, i got this message:

![pdfium](https://user-images.githubusercontent.com/35760382/35390556-2e1d920a-01dc-11e8-846b-56559d5f4753.JPG)

it says that pdfium.dll is not a correct assembly and so i can not use it.

Thank you very much,

Andreas Greiff

**Comment by pvginkel** [comment]
Yeah I was a bit too fast with this. It's still building. I got a few more problems because of API changes which I have fixed. I'll let you know when good versions are up.

**Comment by pvginkel** [comment]
The build completed and looks fine, but I don't yet see some of the NuGet packages up on the website. The version you should look at is `2018.1.25.246`.

**Comment by greiffa** [comment]
the new version 2018.1.25.246 works great, thank you very much :)

**Comment by pvginkel** [comment]
No problem. Sorry for the inconvenience. Lets see how long the Google people can leave their build scripts alone this time.
